### ISSUE TITLE
Expand to the sites

### ISSUE THREAD

**Issue by neshmi** [neshmi/projectmosul#16]
We need to do a little be of reorganisation in preparation to start crowd-sourcing Nimrud and Hatra.

I would like an embedded google map with pins for the sites that are known as destroyed, which then takes a person to the record of that site and the associated photos, artefacts, etc.

**Comment by Howran** [comment]
There are some group about that, we should make a collaboration. I will check if they use a map and make one if not. But it's largly cover

**Comment by Howran** [comment]
Here a reply from one involve in the project :
''The map is limited to Mosul heritage and will have two layers: the first will collect data about all historical architecture in Mosul, the second will summarize only buildings destroyed by the Da´ash gang. The latter should be make for a public access.''

So let me know if we do our own and we use their info for the Mosul part or we wait to see more about.
